$grid = MAIN.$grid;
$level = MAIN.$level;

$modmanager = defined MAIN.$modmanager;
if ($modmanager) {
	$usa = MAIN.$modmanager.Mod_isActive("usa");
	$tokyo = MAIN.$modmanager.Mod_isActive("tokyo");
	$germany = MAIN.$modmanager.Mod_isActive("germany");
	$ulm = MAIN.$modmanager.Mod_isActive("ulm");
	$paris = MAIN.$modmanager.Mod_isActive("paris");
	$stpetersburg = MAIN.$modmanager.Mod_isActive("stpetersburg");
	$london = MAIN.$modmanager.Mod_isActive("london");
}
else {
	$usa = file_exists("addons/usa/buildings/statue-of-liberty/statue-of-liberty.object");
	$tokyo = file_exists("addons/tokyo/buildings/park-tower/park_tower.object");
	$germany = file_exists("addons/germany/buildings/colognedom/colognedom.object");
	$ulm = file_exists("addons/ulm/buildings/library/kuutio.object");
	$paris = file_exists("addons/paris/buildings/eiffel-tower/eiffel_tower.object");
	$stpetersburg = file_exists("addons/stpetersburg/buildings/winter-palace/winter_palace01.object");
	$london = file_exists("addons/london/buildings/bigben-westminster/big_ben.object");
}

// Tokyo
if ($tokyo) {
$level.loadAIVehicle("era4-lorry", "/addons/tokyo/vehicles/era4/lorry/era2_lorry");
}
// USA
if ($usa) {
$level.loadPlayerVehicle("cablecar-01", "/addons/usa/vehicles/se-cablecar/se-cablecar", mkdate(1,1,1970), mkdate(31,12,9999));
$level.loadPlayerVehicle("cablecar-02", "/addons/usa/vehicles/de-cablecar/de-cablecar", mkdate(1,6,1979), mkdate(31,12,9999));
}

// St. Petersburg
if ($stpetersburg) {
$level.loadPlayerVehicle("a-horse-carriage", "/addons/stpetersburg/vehicles/horse-carriage/carriage", mkdate(1,1,1920), mkdate(31,12,9999));
}

//London
if ($london) {
$level.loadPlayerVehicle("a-bus01", "/addons/london/vehicles/bus01/london-bus01", mkdate(1,1,1920), mkdate(31,12,9999));
$level.loadPlayerVehicle("a-bus02", "/addons/london/vehicles/bus02/london-bus04", mkdate(1,1,1920), mkdate(31,12,9999));
$level.loadPlayerVehicle("a-bus03", "/addons/london/vehicles/bus03/bus08", mkdate(1,3,1978), mkdate(31,12,9999));
$level.loadPlayerVehicle("a-bus04", "/addons/london/vehicles/bus04/bus09", mkdate(1,2,1999), mkdate(31,12,9999));
$level.loadPlayerVehicle("a-metro01", "/addons/london/vehicles/metro01/london-metro01", mkdate(1,1,1920), mkdate(31,12,9999));
$grid.loadGridObject("a-metro01b", "addons/london/vehicles/metro01/london-metro01_b.object");
$grid.loadGridObject("a-metro01c", "addons/london/vehicles/metro01/london-metro01_c.object");
}